### ISSUE TITLE
Avoid using sed in /etc/sudoers

### ISSUE THREAD

**Issue by FedericoAntoniazzi** [torniostream/infra#1]
## The problem
It is not recommended to edit /etc/sudoers file to add a group to sudoers.

https://github.com/torniostream/infra/blob/f20a9bedaa7720a6cad2a3b79bf11e2d25bf4199/playbooks/playbook.yml#L20-L26

## What should you do instead
Instead of this you should create a file in /etc/sudoers.d/ (e.g `/etc/sudoers.d/torniostream`) which contains the name of the group you want to add to sudoers and its options.

Example content of /etc/sudoers.d/torniostream:
```
%torniostream ALL=(ALL) NOPASSWD: ALL
```

## Possible implementation using Ansible
```yaml
- name: Add torniostream group to sudoers
  ansible.builtin.copy:
    src: ./torniostream
    dest: /etc/sudoers.d/torniostream
    owner: root
    group: root
    mode: '440'
```

**ATTENTION:** make sure the last line of /etc/sudoers is not commented otherwise sudo won't load the file in its configuraton. Remove the comment or just append `@includedir /etc/sudoers.d` at the end of the file

Pro tip: use `man sudoers` to learn more about sudoers files, folders and import alternatives
